export const URL_BASE = 'http://localhost:3001/api/'
export const URL_BASE_WS = 'http://localhost:3001/api/'
export const URL_ADMIN_SERVER = 'http://localhost:4000/'
export const URL_ADMIN = 'http://localhost:4000/'
export const CLIENT_URL_BASE = 'http://localhost:3000/'
export const URL_BASE_ADMIN_MASTER= 'http://localhost:3003/api/'
