# Employee
type Employee {
    eId: ID
    aId: ID!
    tpId: ID!
    eEnterprise: String
    eSalary: String
    eCharge: String
    typeContract: String
    termContract: String
    eDatAdm: DateTime
    eDatRet: DateTime
    eArl: String
    eBoxComp: String
    eState: Int
    eDatCre: DateTime
    eDatMod: DateTime
    area: Area
    thirdParties: ThirdParties
}
type EmployeeStore {
    eId: ID
    idStore: ID
    id: ID
    idEmployee: ID
    eSalary: Float
    typeContract: String
    uEmail: String
    termContract: String
    eDatAdm: DateTime
    eState: Int
    tpEmail: String

}

# Input
input IEmployee {
    eId: ID
    aId: ID
    tpId: ID
    eEnterprise: String
    eSalary: Float
    eCharge: String
    typeContract: String
    termContract: String
    eDatAdm: DateTime
    eDatRet: DateTime
    eArl: String
    eBoxComp: String
    eState: Int
    tpNumDoc: String
    tpName: String
    tpLasNam: String
    tpPhone: String
    tpEmail: String
    tpState: Int
}
input IEmployeeStore {
    eId: ID
    idStore: ID
    id: ID
    idEmployee: ID
    eSalary: Float
    typeContract: String
    uEmail: String
    tpEmail: String
    termContract: String
    eDatAdm: DateTime
    eState: Int
}

# Query
type Query {
    "Devuelve todos los empleados"
    employees(umId: ID, cId: ID, aId: ID, idStore: ID, max: Int, min: Int): [EmployeeStore]
    employeesFor(umId: ID, cId: ID, aId: ID, idStore: ID, max: Int, min: Int): [Employee]
    "Devuelve un empleado"
    employee(eId: ID, tpId: ID): Employee
    employeeStore(eId: ID, tpId: ID, aId: ID, idStore: ID, max: Int, min: Int): EmployeeStore
}

# Mutation
type Mutation {
    "Esto crea un nuevo empleado"
    createEmployee(input: IEmployee!): Response
    createOneEmployeeStore(input: IEmployeeStore): Response
    createOneEmployeeStoreAndUser(input: IEmployeeStore): Response
    deleteEmployeeStore(eId: ID, tpId: ID, idStore: ID): Response
    

}
