# Types
type TypeFeature {
    thpId: ID!
    thpName: String
    thpIcon: String
    thpState: String
    thpDatCre: String
    thpDatMod: String
}
# Queries
type Query {
    typeFeatures: [TypeFeature]
}
# Inputs
input ITypeFeature {
    thpId: ID!
    thpName: String
    thpIcon: String
    thpState: String
}
# Queries
type Mutation {
    createFeatureType(input: ITypeFeature): TypeFeature
}
