# types
type UserLocation {
    locationId: ID
    id: ID
    cId: ID
    dId: ID
    ctId: ID
    uLatitud: Float
    uLongitude: Float
    uLocationKnow: String
    uPiso: Int
    DatCre: DateTime
    DatMod: DateTime
    pais: Country
    city: City
    department: Department
}
# Inputs
input InputUserLocation {
    locationId: ID
    id: ID
    cId: ID
    dId: ID
    ctId: ID
    uLatitud: Float
    uLongitude: Float
    uLocationKnow: String
    uPiso: Int
    DatCre: DateTime
    DatMod: DateTime
}
input IDeleteUserLocation {
    locationId: ID
}

# Queries
type Query {
    getUserLocations: [UserLocation]
}

# Mutations
type Mutation {
    "Registra una location"
    updateUserLocations(input: InputUserLocation): UserLocation
    "Borra un location"
    deleteUserLocations(locationId: ID, uLocationState:Int): Response
}
