type StoreSchedule {
  idStore: ID
  schId: ID
  id: ID
  schDay: Int
  schHoSta: String
  schHoEnd: String
  schState: Int
  store: Store

}
input ITstoreSchedule {
  schId: ID
  id: ID
  idStore: ID
  schDay: Int
  schHoSta: String
  schHoEnd: String
  schState: Int
}
input IsStoreSchedule {
  schData: [ITstoreSchedule]

}

type Query {
  getStoreSchedules(schDay: Int, schState: Int, idStore: ID): [StoreSchedule]
  getOneStoreSchedules(schDay: Int, schState: Int, idStore: ID): StoreSchedule
}

type Mutation {
  setStoreScheduleReserve(input: IsStoreSchedule!): [StoreSchedule]
  setStoreSchedule(input: ITstoreSchedule!): Response
}