name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Check code
      run: npm run check:eslint -f
    - name: Install dependencies
      run: npm install -no-audit --no-fund --no-optional -f
    - name: Build
      run: npm run build -f
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-project-id: 'prj_uTc94XNPVyUlJky2VtqMdeNmRRm6'
        vercel-org-id: 'prj_uTc94XNPVyUlJky2VtqMdeNmRRm6'