name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install -no-audit --no-fund --no-optional -f
    - run: npm run check:eslint -f
    - name: Build
      run: npm run build -f

  login-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/production/Dockerfile
        push: true
        tags: juvinaojesus/front-admin-store
